name: Generate Doxygen Documentation

on:
  push:
    tags:
      - "v*"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate documentation
        working-directory: laboratories/cicd-documentation
        run: doxygen

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html-docs
          path: laboratories/cicd-documentation/html/
